// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PneumaticsModuleType;
import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import edu.wpi.first.wpilibj.motorcontrol.Spark;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class arm extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private DoubleSolenoid front1;
private DoubleSolenoid front2;
private DoubleSolenoid back1;
private DoubleSolenoid back2;
private Encoder armencoder;
private Spark extendmotor;
private Spark retractmotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public arm() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
front1 = new DoubleSolenoid(0, PneumaticsModuleType.CTREPCM, 0, 1);
 addChild("front 1", front1);
 

front2 = new DoubleSolenoid(0, PneumaticsModuleType.CTREPCM, 2, 3);
 addChild("front 2", front2);
 

back1 = new DoubleSolenoid(0, PneumaticsModuleType.CTREPCM, 4, 5);
 addChild("back 1", back1);
 

back2 = new DoubleSolenoid(0, PneumaticsModuleType.CTREPCM, 6, 7);
 addChild("back 2", back2);
 

armencoder = new Encoder(4, 5, false, EncodingType.k4X);
 addChild("arm encoder",armencoder);
 armencoder.setDistancePerPulse(1.0);

extendmotor = new Spark(0);
 addChild("extend motor",extendmotor);
 extendmotor.setInverted(false);

retractmotor = new Spark(1);
 addChild("retract motor",retractmotor);
 retractmotor.setInverted(false);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

