// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// User note: robotbuilder no longer in use, all code must be edited by a user

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import java.util.function.DoubleSupplier;
import frc.robot.commands.open;
import frc.robot.commands.DriveDistance;
import frc.robot.commands.ArmExtendDistance;
import frc.robot.subsystems.driveTrain;
import frc.robot.commands.tiltdownback;
import frc.robot.commands.tiltdownfront;
import frc.robot.commands.tiltupback;
import frc.robot.commands.tiltupfront;
import frc.robot.commands.close;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.Constants.AutoConstants;
import frc.robot.subsystems.claw;
import frc.robot.subsystems.driveTrain;
import frc.robot.subsystems.arm;
/**
 *
 */
public class AutonomousCommand extends SequentialCommandGroup {

/**
 * @param drive 
 * @param pincer
 * @param reacher
 */

    public AutonomousCommand(driveTrain drive, arm reacher, claw pincer ) {
        addCommands(
            new ArmExtendDistance(AutoConstants.kAutoArmExtendDistance, reacher),
            new open (pincer),
            new DriveDistance(AutoConstants.kAutoBackupDistanceInches, AutoConstants.kAutoDriveSpeed, drive)
        );


    
    }
    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
