// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
  

  public static final class DriveConstants {
    public static final int kEncoderCPR = 1024;
    public static final double kWheelDiameterInches = 6;
    public static final double kEncoderDistancePerPulse =
        // Assumes the encoders are directly mounted on the wheel shafts
        (kWheelDiameterInches * Math.PI) / (double) kEncoderCPR;
  }

  

  public static final class AutoConstants {
    public static final double kAutoDriveDistanceInches = 60; //need to change
    public static final double kAutoBackupDistanceInches = 20; //need to change
    public static final double kAutoTurnAngle = 90;
    public static final double kAutoDriveSpeed = 0.5;

    public static final double kAutoArmExtendDistance = 20; //may need to change
    public static final double kAutoArmRetractDistance = 20; //may need to change
  }

  public static final class ArmConstants {
    public static final int kArmEncoderCPR = 1024;
    public static final double kGearDiameterInches = 3; //diameter of the gear or otherwise component that results in arm movement
    public static final double kArmEncoderDistanceperPulse = (kGearDiameterInches * Math.PI) / (double) kArmEncoderCPR;
  }


}

